Feature/lnd ens
NOAA-PSL/land-apply_jedi_incr pull request #6
Opened 2024-10-24 08:04 UTC by tsga

Revisions to the add_jedi_incr to run it with
- any number of MPI processes (instead of 6)
- an arbitrary number of tiles (regional grids can have only 1 tile)
with minimal/one change to the calling script (DA_update/do_landDA.sh). 
Other changes are diagnostic to help catch any input errors.

The only change to DA_update/do_landDA.sh sets frac_grid in apply_incr_nml as logical (frac_grid=.false.) instead of "YES/NO" 

The land-offline_workflow tests pass (tested with 6, 5, and 1 processes running apply_incr.exe)

2024-10-24 12:40 UTC, tsga commented
Tagging @ClaraDraper-NOAA just to notify

2024-11-06 21:20 UTC, ClaraDraper-NOAA requested changes
Thanks @tsga , looks good to me. 

Can you please delete all the code that you've commented out? I started marking it, but there's more.

2024-11-06 21:20 UTC, ClaraDraper-NOAA commented on sorc/apply_incr_noahmp_snow.f90
> +    ! uncommenting this may help catch a namelist error
can you please delete the commented code block?

2024-11-06 21:20 UTC, ClaraDraper-NOAA commented on sorc/apply_incr_noahmp_snow.f90
> +    ! write (6, *) 'calculate mapping from land mask in ', trim(restart_file)
please delete this.

2024-11-06 21:20 UTC, ClaraDraper-NOAA commented on sorc/apply_incr_noahmp_snow.f90
> + subroutine read_fv3_restart(restart_file, res, ncid, &                      !tile_num, rst_path, date_str, hour_str,
Can you please delete the comments here?

2024-11-06 21:20 UTC, ClaraDraper-NOAA commented on sorc/apply_incr_noahmp_snow.f90
> +!  character(len=8), intent(in) :: date_str
remove commented code. And below.

2024-11-07 22:34 UTC, TravisElless-NOAA approved these changes
Things look okay to me

2024-11-08 21:05 UTC, ClaraDraper-NOAA commented
thanks @tsga . Merging it now. When you submit the update to the landDA repo with the updated data type, please update the hash to this repo.

2024-11-08 21:05 UTC, merged